server.port=9090
spring.application.name=Review
# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://mayurkotwal75:rentcart123@rentcart.rpnqlbb.mongodb.net/rentcart?retryWrites=true&w=majority&appName=RentCart